config/routes.rb
Rails.application.routes.draw do

  namespace :blog do
    get '', to: 'welcome#index', as: '/'
    resources :comments
    resources :posts
    get '/tag/:tag', to: 'posts#list_by_tag', as: 'tag'
  end

  namespace :admin do
    resources :jobs do
      resources :candidates, only: [:index]
    end
    get "/users", to: "users#index"
    delete "/user/:id", to: "users#destroy", as: :user
  end
  resources :jobs, only: [:index,:show] do
    resources :candidates, only: [:new, :create]
  end

  resources :horses

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users do
    resource :profile
  end

  resources :contacts
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy

  before_validation :generate_permalink
  before_save :save_html

  validates :permalink, uniqueness: true

  has_attached_file :image, :styles => { :large => "400x300>", :medium => "230x150>" }, :default_url => "/images/:style/missing.png",
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :dropbox_visibility => 'public'
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def generate_permalink
  	self.permalink = title.parameterize
  end

  def save_html
  	md  = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new, extensions = {})
  	write_attribute :html, md.render(markdown)
  end

  def to_param
    permalink
  end

end

app/controllers/blog/comments_controller.rb
class Blog::CommentsController < ApplicationController

  before_filter :require_sign_in
  before_action :authenticate_user!
  # skip_before_filter  :verify_authenticity_token
  before_action :creator?, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    @post = @comment.post
    @comment.save
    respond_to do |format|
      format.js
    end
  end

  def edit
    @comment = Comment.find_by(id: params[:id])
    respond_to do |format|
      format.js
    end

  end

  def update
    @comment = Comment.find_by(id: params[:id])
    @post = @comment.post
    respond_to do |format|
      if @comment.update(comment_params)
        format.js
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to blog_post_url(@comment.post), notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body,:attachment,:user_id,:post_id)
    end

    def creator?
      @comment = Comment.find_by(id: params[:id])
      unless current_user == @comment.user
        redirect_to blog_post_url(@comment.post)
        flash[:notice] = "You are authorized to commit any action to this comment."
      end
    end
end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :create, :destroy]
  before_filter :find_post, only: [:show,:edit,:update,:destroy]
  before_filter :require_sign_in
  before_filter :admin_user?, except: [:show, :list_by_tag]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 15)
    @user = User.find_by(params[:user_id])
  end

  # GET /posts/i-am-an-aweome-post-man
  def show
    @blog = true
    @comment = Comment.new( :post => @post )
    @tags = @post.tags.split(",").map(&:to_s)
  end

  # GET /posts/new
  def new
    new_post
  end

  # GET /posts/1/edit
  def edit
  end

  def create
    if new_post(post_params).save
      redirect_to blog_posts_url, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to blog_posts_url, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def list_by_tag
    @tag = params[:tag]
    @posts = Post.where("tags LIKE ?", "%#{@tag}%")
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def find_post
      @post = Post.find_by_permalink(params[:id])
    end

    def new_post(attrs={})
      @post ||= current_user.posts.new(attrs)
    end

    def post_params
      params.require(:post).permit(:title, :markdown, :published_at, :tags, :image)
    end
end

app/controllers/blog/welcome_controller.rb
class Blog::WelcomeController < ApplicationController
  before_filter :require_sign_in

  def index
    @blog = true
    @posts = Post.paginate(:page => params[:page],:per_page => 15)
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/posts/_comments.html.erb
<% @post.comments.each do |comment| %>
  <div class="row comment">
    <div class="row comment-creator">
      <div class="col-sm-1 text-center">
        <%= image_tag comment.user.profile.avatar.url(:thumb), class:"thumbnail" %>
      </div>
      <div class="col-sm-11">
        <div class="row">
          <div class="col-sm-9">
            <p class="fullname"><%= current_user.profile.first_name %> <%= current_user.profile.last_name %></p>
            <span class="datetime"> <%= l comment.created_at, format: :datetime %> </span>
          </div>
          <div class="col-sm-3 post-actions text-right">
            <% if current_user == comment.user %>
              <%= link_to "Edit comment", edit_blog_comment_path(comment), remote: true %> |
              <%= link_to "Delete", blog_comment_path(comment), method: :delete, data: { confirm: "You sure?" } %>
            <% end %>
          </div>
        </div>

        <div class="well row comments-well">
          <div class="col-sm-10">
            <%= comment.body %>
          </div>
          <% if comment.attachment? %>
            <div class="col-sm-2 text-center">
              <%= image_tag comment.attachment.url(:thumb) %>
              <span>attachment</span>
            </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>

<% end %>

app/views/blog/posts/_form.html.erb
<%= form_for [:blog,@post] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group well">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group well">
      <%= f.label :image %>
       <%= f.file_field :image, class: 'form-control' %>
  </div>
  <div class="form-group well">
    <%= f.label :markdown %><br>
    <%= f.text_area :markdown,size: "60x10" , class: 'form-control'%>
  </div>
  <div class="form-group well">
    <%= f.label :tags %><br>
    <%= f.text_field :tags, class: 'form-control' %>
  </div>
  <div class="field well">
    <%= f.label :user_id %><br>
    <%= f.hidden_field :user_id %>
    <%= current_user.profile.first_name %> <%= current_user.profile.last_name %>
  </div>
  <div class="form-group well">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at , class: 'form-control'%>
  </div>
  <div class="actions">
    <%= f.submit "Save" , class:"btn btn-success" %> <%= link_to 'Back', blog_posts_path, class:"btn btn-warning" %>
  </div>
<% end %>

app/views/blog/posts/edit.html.erb
<div class="all-posts-bg">
  <div class="well">
    <h1>Editing Post</h1>
  </div>


  <%= render 'form' %>
</div>

app/views/blog/posts/index.html.erb
<% if !current_user.profile.nil? %>
  <div class="all-posts-bg">
      <div class="well">
        <h1>Listing Posts</h1>
      </div>

    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Markdown</th>
            <th>User</th>
            <th>Tags</th>
            <th>Published at</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><%= post.title %></td>
              <td><%= truncate(post.markdown, length: 70) %></td>
              <td><%= post.user.profile.first_name %></td>
              <td><%= post.tags %></td>
              <td><%= post.published_at %></td>
              <td><%= link_to 'Show', blog_post_path(post), class: 'btn btn-success ' %></td>
              <td><%= link_to 'Edit', edit_blog_post_path(post), class: 'btn btn-warning ' %></td>
              <td><%= link_to 'Destroy', blog_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger ' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Post', new_blog_post_path , class: 'btn btn-success '%> <%= link_to "Back", blog_path , class: 'btn btn-warning '%>
    </div>
  </div>
<% else %>
  <div class="well">
    <p>
      Please go here and complete your profile in order to manage posts.
      <%= link_to "Profile", new_user_profile_path(current_user) %>
    </p>
  </div>
<% end %>

<div class="row">
  <div class="col-sm-12 text-center">
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/blog/posts/list_by_tag.html.erb
<div class="row">
  <div class="col-sm-12 well">
    <h4>Listing all posts by tag - <span class="tag"><%= @tag %></span></h4>
  </div>
</div>
<div class="row">
  <div class="col-sm-12 posts-container">
    <% @posts.each do |post| %>
    <div class="row">
      <div class="col-sm-12">
        <div class="well blog_posts">

          <div class="well-body">
            <div class="row">
              <div class="col-sm-3 text-center">
                <% if post.image_file_name.nil? %>
                  <img src="http://placehold.it/230x150" alt="" />
                <% else %>
                  <%= image_tag post.image.url(:medium), class: "thumbnail" %>
                <% end %>

              </div>
              <div class="col-sm-9">
                <h4 class="well-title"><%= link_to post.title, blog_post_path(post) %></h4>
                <%= truncate(sanitize(post.markdown), length: 220) %>
                <div class="row post-more-details">
                  <div class="col-sm-10">
                    <span>Published:</span> <%= l post.published_at, :format => :date %> |
                    <% if post.comments.count > 0 %>
                      <span> <%= pluralize(post.comments.count, "comment") %> </span>
                    <% else %>
                      <span> 0 comments</span>
                    <% end %>
                  </div>
                  <div class="col-sm-2">
                    <%= link_to "Read More...", blog_post_path(post), class:"btn btn-primary" %>
                  </div>
                </div>

              </div>
            </div>

          </div>
        </div>
      </div>
    </div>

    <% end %>
  </div>
</div>

app/views/blog/posts/new.html.erb
<div class="all-posts-bg">
  <div class="well">
    <h1>New Post</h1>
  </div>

  <%= render 'form' %>
</div>

app/views/blog/posts/show.html.erb
<div class="row post">
  <hr>
  <div class="col-sm-10 col-sm-offset-1">

    <h1 class="text-center post-title"><%= @post.title %></h1>
    <hr class="style">
    <div class="post-details text-center">
      <span class="date"><%= l @post.created_at, :format => :date %></span><br>
      <span class="author">By
        <%= @post.user.profile.first_name %>
        <%= @post.user.profile.last_name %></span>
    </div>

    <% if !@post.image_file_name.nil? %>
      <div class="text-center image">
        <%= image_tag @post.image.url(:large) %>
      </div>
    <% end %>

    <div class="post-body">
      <%= raw @post.html %>
      <hr>
    </div>
    <div class="post-tags text-right">
      <ul>
        Tags:<% @tags.each do |t| %>
        <a href="#">
          <li><%= link_to t, blog_tag_path(t) %></li>
        </a>
        <% end %>
      </ul>
    </div>
    <div class="row">
      <div class="post-comments col-sm-12">
        <% if current_user.profile.nil? %>
        <div class="row col-sm-12 text-center">
          <p>
            You need to complete your profile in order to post comments
          </p>
          <%= link_to "Complete Profile", new_user_profile_path(current_user), class: "btn btn-primary btn-lg" %>
        </div>

        <% elsif !current_user.profile.nil? && current_user.profile.avatar_file_name.nil? %>
        <div class="row col-sm-12 text-center">
          <p>
            An image/avatar is required to post comments
          </p>
          <%= link_to "Go to Profile", edit_user_profile_path(current_user), class: "btn btn-warning btn-lg" %>
        </div>

        <% else %>
        <div class="row make-comment display-none">
          <div class="col-sm-12">
            <%= render "blog/comments/comment_form" %>
          </div>
        </div>
          <div class="row all-comments">
            <% if @post.comments.count > 0 %>
                <div class="row current-comments">
                  <div class="col-sm-12">
                    <div class="row">
                      <div class="col-sm-6 col-sm-offset-3">
                        <button type="button" name="button" class="btn btn-primary btn-block newcomment">COMMENT</button>
                      </div>
                    </div>
                    <div class="div comments-partial">
                        <%= render :partial => 'comments' , post: @post %>
                    </div>
                  </div>
                </div>

            <% else %>
              <div class="row no-comment">
                <div class="col-sm-12">
                  <div class="row">
                    <div class="col-sm-12 text-center">
                      <div class="no-comment-body">
                        <p> No comment. Be the first!</p>
                        <button type="button" name="button" class="btn btn-warning btn-block newcomment">COMMENT</button>
                      </div>
                    </div>
                  </div>

                  <div class="div comments-partial">

                  </div>
                </div>
              </div>
            <% end %>
          </div>

        <% end %>
      </div>
    </div>

    <div class="edit_container display-none">

    </div>
  </div>

</div>