config/routes.rb
Rails.application.routes.draw do

  namespace :blog do
    get '', to: 'welcome#index', as: '/'
    resources :comments
    resources :posts
    get '/tag/:tag', to: 'posts#list_by_tag', as: 'tag'
  end

  namespace :admin do
    resources :jobs do
      resources :candidates, only: [:index]
    end
    get "/users", to: "users#index"
    delete "/user/:id", to: "users#destroy", as: :user
  end
  resources :jobs, only: [:index,:show] do
    resources :candidates, only: [:new, :create]
  end

  resources :horses

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users do
    resource :profile
  end

  resources :contacts
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  get '/about' => 'pages#about'
  root 'pages#home'

end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController

  # GET /horses
  def index
    all_horses
  end

  # GET /horses/1
  def show
    horse
  end

  # GET /horses/new
  def new
    new_horse
  end
  
  # POST /horses
  def create
    if new_horse(horse_params).save
        redirect_to new_horse, notice: 'Horse was successfully created.'
    else
      render :new
    end
  end

# GET /horses/1/edit
  def edit
     horse
  end

  # PATCH/PUT /horses/1
  def update
    if horse.update(horse_params)
      redirect_to horse, notice: 'Horse was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /horses/1
  # DELETE /horses/1.json
  def destroy
    @horse.destroy
    redirect_to horses_url, notice: 'Horse was successfully destroyed.'
  end

private

  def all_horses
    @horse ||= Horse.all
  end

  def new_horse(attrs={})
    @horse ||= Horse.new(attrs)
  end

  def horse
    @horse ||= Horse.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def horse_params
    params.require(:horse).permit(:height, :name, :color)
  end
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/views/horses/_form.html.erb
<%= form_for(@horse) do |f| %>
  <% if @horse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

      <ul>
      <% @horse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/horses/edit.html.erb
<h1>Editing Horse</h1>

<%= render partial: 'form', locals: { horse: @horse } %>

<%= link_to 'Show', @horse %> |
<%= link_to 'Back', horses_path %>

app/views/horses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Horses</h1>

<table>
  <thead>
    <tr>
      <th>Height</th>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @horses.each do |horse| %>
      <tr>
        <td><%= horse.height %></td>
        <td><%= horse.name %></td>
        <td><%= horse.color %></td>
        <td><%= link_to 'Show', horse %></td>
        <td><%= link_to 'Edit', edit_horse_path(horse) %></td>
        <td><%= link_to 'Destroy', horse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Horse', new_horse_path %>

app/views/horses/new.html.erb
<h1>New Horse</h1>

<%= render partial: 'form', locals: { horse: @horse } %>

<%= link_to 'Back', horses_path %>

app/views/horses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @horse.name %>
</p>

<p>
  <strong>Height:</strong>
  <%= @horse.height %>
</p>



<p>
  <strong>Color:</strong>
  <%= @horse.color %>
</p>

<%= link_to 'Edit', edit_horse_path(@horse) %> |
<%= link_to 'Back', horses_path %>