config/routes.rb
Rails.application.routes.draw do

  namespace :blog do
    get '', to: 'welcome#index', as: '/'
    resources :comments
    resources :posts
    get '/tag/:tag', to: 'posts#list_by_tag', as: 'tag'
  end

  namespace :admin do
    resources :jobs do
      resources :candidates, only: [:index]
    end
    get "/users", to: "users#index"
    delete "/user/:id", to: "users#destroy", as: :user
  end
  resources :jobs, only: [:index,:show] do
    resources :candidates, only: [:new, :create]
  end

  resources :horses

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users do
    resource :profile
  end

  resources :contacts
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :candidates
  before_save :save_html

  def save_html
  	md  = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new, extensions = {})
  	write_attribute :description, md.render(description)
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < Admin::BaseController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to admin_jobs_url, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to admin_jobs_url, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to admin_jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :kind, :category, :salary, :contact, :company)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find_by_id(params[:id])
  end
end

app/views/admin/jobs/_form.html.erb
<%= form_for [:admin, @job] do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group well">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group well">
    <%= f.label :description %><br>
    <%= f.text_area :description,size: "60x10" , class: 'form-control'%>
  </div>
  <div class="form-group well">
    <%= f.label :company %><br>
    <%= f.text_field :company, class: 'form-control' %>
  </div>
  <div class="form-group well">
    <%= f.label :salary %><br>
    <%= f.text_field :salary, class: 'form-control'%>
  </div>
  <div class="form-group well">
    <%= f.label :kind, "Type" %><br>
    <%= f.text_field :kind, class: 'form-control', placeholder: "e.g part-time/full-time"%>
  </div>
  <div class="form-group well">
    <%= f.label :category %><br>
    <%= f.text_field :category, class: 'form-control', placeholder: "e.g IT sector"%>
  </div>
  <div class="form-group well">
    <%= f.label :contact %><br>
    <%= f.text_field :contact, class: 'form-control', placeholder: "e.g example@example.com"%>
  </div>

  <div class="actions text-center">
    <%= f.submit "Save", class:"btn btn-success" %>
  </div>
<% end %>

app/views/admin/jobs/edit.html.erb
<div class="well">
  <h1>Editing Job</h1>

  <%= render 'form' %>
</div>

app/views/admin/jobs/index.html.erb
<div class="well">
  <h1>Listing Jobs</h1>


    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Company</th>
          <th>Salary</th>
          <th>Type</th>
          <th>Category</th>
          <th>Contact</th>
          <th>No. of candidates</th>
        </tr>
      </thead>

      <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td><%= job.title %></td>
            <td><%= truncate(job.description, length: 100) %></td>
            <td><%= job.company %></td>
            <td><%= job.salary %></td>
            <td><%= job.kind %></td>
            <td><%= job.category %></td>
            <td><%= job.contact %></td>
            <td><%= job.candidates.count %></td>
            <td>
              <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  Actions
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  <li><%= link_to 'Candidates', admin_job_candidates_path(job) %></li>
                  <li><%= link_to 'View', job_path(job) %></li>
                  <li><%= link_to 'Edit', edit_admin_job_path(job) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Destroy', admin_job_path(job), method: :delete, data: { confirm: 'Are you sure?' } %></li>
                </ul>
              </div>

            </td>
          </tr>
        <% end %>
      </tbody>
    </table>


  <br>

  <%= link_to 'New Job', new_admin_job_path, class: "btn btn-info" %>
</div>

app/views/admin/jobs/new.html.erb
<div class="well">
  <h1>New Job</h1>

  <%= render 'form' %>
</div>