config/routes.rb
Rails.application.routes.draw do

  namespace :blog do
    get '', to: 'welcome#index', as: '/'
    resources :comments
    resources :posts
    get '/tag/:tag', to: 'posts#list_by_tag', as: 'tag'
  end

  namespace :admin do
    resources :jobs do
      resources :candidates, only: [:index]
    end
    get "/users", to: "users#index"
    delete "/user/:id", to: "users#destroy", as: :user
  end
  resources :jobs, only: [:index,:show] do
    resources :candidates, only: [:new, :create]
  end

  resources :horses

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :users do
    resource :profile
  end

  resources :contacts
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  has_many :posts
  has_many :comments
  has_many :messages
  has_many :conversations, foreign_key: :sender_id
  attr_accessor :stripe_card_token

  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.includes(:profile).order("id ASC")
  end

  def destroy
    user = User.find_by_id(params[:id])
    if user.destroy
      flash[:notice] = "Success! User deleted."
    else
      flash[:alert] = "Something went wrong!"
    end
    redirect_to :back
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :select_plan, only: :new


  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end
 

 private

  def select_plan
    return if params[:plan] && Plan.all.pluck(:id).include?(params[:plan].to_i)

    flash[:notice] = "Please select a membership plan to sign up."
    redirect_to root_url
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def index
  	@users = User.includes(:profile)
  end


  def show
    @user = User.find( params[:id] )

    session[:conversations] ||= []

    # @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])
  end
end

app/helpers/users_helper.rb
module UsersHelper
	
	def job_title_icon
if @user.profile.job_title == "Developer"
	"<i class='fa fa-code'></i>".html_safe
elsif @user.profile.job_title == "Entrepreneur"
		"<i class='fa fa-lightbulb-o'></i>".html_safe
elsif @user.profile.job_title == "Investor"
	"<i class='fa fa-dollar'></i>".html_safe
	
end
end
end

app/views/admin/users/index.html.erb
<div class="table-responsive" id="manage-users">
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Email</th>
        <th>Name</th>
        <th>Surname</th>
        <th>Job title</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |u| %>
        <tr>
          <td> <%= u.id %> </td>
          <td> <%= u.email %> </td>
          <% if !u.profile.nil? %>
            <td><%= u.profile.first_name.nil?  ? "None provided" : u.profile.first_name %></td>
            <td><%= u.profile.last_name.nil?  ? "None provided" : u.profile.last_name %></td>
            <td><%= u.profile.job_title.nil? ? "None provided" : u.profile.job_title %></td>
          <% else %>
            <td>Profile not configured</td>
            <td>Profile not configured</td>
            <td>Profile not configured</td>
          <% end %>
          <td><%= link_to 'Destroy', admin_user_path(u), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger ' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>